title: Olaf Pineda # your name (or website title) here
logo: "/images/olaflogo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Economist|Data Analyst <br><br> Economist with 8+ years of experience as a macroeconomic data analyst in the public sector,
  and 4 years of experience in university teaching. <br>
  I am passionate about macroeconomics and data analysis. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/olafpineda/">LinkedIn Profile</a> 
  <br><br>
remote_theme: pages-themes/minimal@v0.2.0

google_analytics: UA-000000-0 # your Google Analytics tracking ID here
